- name: Install desktop
  pacman:
    name:
    - network-manager-applet
    - ttf-inconsolata
    - ttf-linux-libertine
    - trash-cli
    - zathura
    - zathura-pdf-mupdf
    - i3-gaps
    - feh
    - sxiv
    - kitty
    - emacs 
    - gimp
    state: latest

- name: Install tools from AUR 
  become: yes
  become_user: ansible
  aur:
    name:
    - ttf-emojione
    - ttf-symbola
    skip_installed: true

# vim: ts=2 sw=2 et :
