- name: Add ansible user
  user:
    name: ansible
    group: wheel

- name: Ansible user can do pacman things
  lineinfile:
    path: /etc/sudoers.d/11-ansible
    line: 'ansible ALL=(ALL) NOPASSWD: /usr/bin/pacman'
    create: yes
    validate: 'visudo -cf %s'

- name: "pacman -Syu"
  pacman:
    update_cache: yes
    upgrade: yes 

- name: Install common tools
  pacman:
    name: 
    - base-devel
    - polkit
    - haveged
    - openssh
    - rofi
    - tree
    - git
    - htop
    - neovim
    - feh
    - ranger
    state: latest

- name: Ensure haveged is running so sshd has some entropy
  systemd:
    name: haveged
    enabled: yes
    state: started

- name: Ensure sshd is running
  systemd:
    name: sshd
    enabled: yes
    state: started

# vim: ts=2 sw=2 et :
